"""
ADS OS -- Report Engine (Sprint 3)
Generates a professional Project Summary Report as a PDF, using only data
that genuinely exists: Client + Project details, Milestones, Planning
(Floors/Spaces/Area Coverage), and Site Visits.

This deliberately does NOT attempt the full "Report Center" (16 report types,
checkbox section builder, saved templates, role-based visibility) from the
source document -- most of those report types need Design/Commercial/
Execution data (deliverables, drawings, BOQ, payments, site instructions)
that doesn't exist yet. Building a section-picker with checkboxes for empty
sections would be worse than no report builder at all. This module is
structured so those sections can be added later without restructuring.
"""
import os
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib.colors import HexColor
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_RIGHT
from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
                                 Image, PageBreak, HRFlowable)
from reportlab.platypus.flowables import Flowable
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

import db

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
LOGO_PATH = os.path.join(BASE_DIR, "assets", "logo.png")
FONT_DIR = os.path.join(BASE_DIR, "assets", "fonts")

# Bug fix: the standard PDF base-14 fonts (Helvetica etc.) have no glyph for
# the Rupee sign (₹, U+20B9) -- it silently rendered as a black box. DejaVu
# Sans has full Unicode coverage including currency symbols, so registering
# it and using it everywhere text is drawn fixes this properly instead of
# falling back to "Rs." as plain text.
FONT_REGULAR = "Helvetica"
FONT_BOLD = "Helvetica-Bold"
_regular_path = os.path.join(FONT_DIR, "DejaVuSans.ttf")
_bold_path = os.path.join(FONT_DIR, "DejaVuSans-Bold.ttf")
if os.path.exists(_regular_path) and os.path.exists(_bold_path):
    pdfmetrics.registerFont(TTFont("DejaVuSans", _regular_path))
    pdfmetrics.registerFont(TTFont("DejaVuSans-Bold", _bold_path))
    FONT_REGULAR = "DejaVuSans"
    FONT_BOLD = "DejaVuSans-Bold"

BRASS = HexColor("#B68100")
INK = HexColor("#1A1A1A")
MUTED = HexColor("#6B6B6B")
WHITE = HexColor("#FFFFFF")
PARCHMENT = HexColor("#F5F0E6")


def _get_styles():
    styles = getSampleStyleSheet()
    # Bug fix: fontSize was set without explicit leading -- ReportLab's
    # ParagraphStyle defaults leading to 12pt regardless of font size, so a
    # 20pt title only reserved 12pt of vertical space and the next paragraph
    # drew straight through it. Leading is now always >= 1.2x the font size.
    styles.add(ParagraphStyle("ADSTitle", fontName=FONT_BOLD, fontSize=20,
                              leading=24, textColor=INK, spaceAfter=4))
    styles.add(ParagraphStyle("ADSSubtitle", fontName=FONT_REGULAR, fontSize=10,
                              leading=13, textColor=MUTED, spaceAfter=12))
    styles.add(ParagraphStyle("ADSSection", fontName=FONT_BOLD, fontSize=13,
                              leading=16, textColor=BRASS, spaceBefore=16, spaceAfter=8))
    styles.add(ParagraphStyle("ADSBody", fontName=FONT_REGULAR, fontSize=9.5,
                              leading=13, textColor=INK))
    styles.add(ParagraphStyle("ADSSmall", fontName=FONT_REGULAR, fontSize=8,
                              leading=10, textColor=MUTED))
    return styles


def _footer(canvas, doc):
    canvas.saveState()
    canvas.setFont(FONT_REGULAR, 7.5)
    canvas.setFillColor(MUTED)
    canvas.drawString(20 * mm, 12 * mm,
                      f"Confidential — Generated by ADS OS on {datetime.now().strftime('%d %b %Y, %I:%M %p')}")
    canvas.drawRightString(190 * mm, 12 * mm, f"Page {doc.page}")
    canvas.restoreState()


def _info_table(rows, col_widths=(55 * mm, 105 * mm)):
    styles = _get_styles()
    data = []
    for label, value in rows:
        data.append([Paragraph(f"<b>{label}</b>", styles["ADSBody"]),
                     Paragraph(str(value) if value not in (None, "") else "—", styles["ADSBody"])])
    t = Table(data, colWidths=col_widths)
    t.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("LINEBELOW", (0, 0), (-1, -1), 0.4, PARCHMENT),
    ]))
    return t


def generate_project_summary_report(project_id, output_path):
    """
    Builds the Project Summary Report PDF. Returns the output_path on success.
    """
    styles = _get_styles()

    project = db.fetch_one("""
        SELECT p.*, c.ClientName, c.Mobile, c.MobileCountryCode, c.Email,
               sec.SectorName, svc.ServiceName
        FROM tblProject p
        JOIN tblClient c ON p.ClientID = c.ClientID
        LEFT JOIN mstSector sec ON p.SectorID = sec.SectorID
        LEFT JOIN mstService svc ON p.ServiceID = svc.ServiceID
        WHERE p.ProjectID = ?
    """, (project_id,))
    if not project:
        raise ValueError(f"Project {project_id} not found")

    pkg_name = "Not set"
    if project["DefaultPackageID"]:
        pkg = db.fetch_one("SELECT PackageName FROM mstPackage WHERE PackageID=?", (project["DefaultPackageID"],))
        if pkg:
            pkg_name = pkg["PackageName"]

    milestones = db.fetch_all("SELECT * FROM tblMilestone WHERE ProjectID=? ORDER BY MilestoneOrder", (project_id,))
    floors = db.fetch_all("SELECT * FROM tblFloor WHERE ProjectID=? ORDER BY FloorOrder", (project_id,))
    site_visits = db.fetch_all("SELECT * FROM trxSiteVisit WHERE ProjectID=? ORDER BY VisitDate DESC", (project_id,))

    doc = SimpleDocTemplate(output_path, pagesize=A4,
                            topMargin=18 * mm, bottomMargin=18 * mm,
                            leftMargin=20 * mm, rightMargin=20 * mm)
    story = []

    # ---------------- Header / Cover ----------------
    if os.path.exists(LOGO_PATH):
        logo = Image(LOGO_PATH, width=55 * mm, height=(55 * mm * 311 / 906))
        story.append(logo)
        story.append(Spacer(1, 10 * mm))

    story.append(Paragraph(project["ProjectName"], styles["ADSTitle"]))
    story.append(Paragraph(f"{project['ProjectCode']}  ·  Project Summary Report  ·  "
                           f"Generated {datetime.now().strftime('%d %B %Y')}", styles["ADSSubtitle"]))
    story.append(HRFlowable(width="100%", thickness=1, color=BRASS, spaceAfter=10))

    # ---------------- Project Information ----------------
    story.append(Paragraph("Project Information", styles["ADSSection"]))
    mobile_display = f"{project['MobileCountryCode'] or ''} {project['Mobile'] or ''}".strip()
    story.append(_info_table([
        ("Client", project["ClientName"]),
        ("Contact", f"{mobile_display}  ·  {project['Email'] or '—'}"),
        ("Sector", project["SectorName"] or "—"),
        ("Service", project["ServiceName"] or "—"),
        ("Status", project["ProjectStatus"]),
        ("Site Address", project["SiteAddress"] or "—"),
        ("Total Built-up Area", f"{project['TotalBuiltUpArea']} {project['Unit']}"),
        ("Default Package", pkg_name),
        ("Start Date", project["StartDate"] or "—"),
        ("Expected Completion", project["ExpectedCompletion"] or "—"),
    ]))

    # ---------------- Milestone Progress ----------------
    if milestones:
        story.append(Paragraph("Milestone Progress", styles["ADSSection"]))
        completed = sum(1 for m in milestones if m["Status"] == "Completed")
        story.append(Paragraph(f"{completed} of {len(milestones)} milestones completed", styles["ADSBody"]))
        story.append(Spacer(1, 4))
        rows = [["#", "Milestone", "Status", "Completed On"]]
        for m in milestones:
            rows.append([str(m["MilestoneOrder"]), m["MilestoneName"], m["Status"], m["CompletedOn"] or "—"])
        t = Table(rows, colWidths=[10 * mm, 75 * mm, 40 * mm, 35 * mm])
        t.setStyle(_table_style(header_bg=INK))
        story.append(t)

    # ---------------- Planning Summary (Floors & Spaces) ----------------
    if floors:
        story.append(Paragraph("Planning Summary", styles["ADSSection"]))
        total_floor_area = 0
        total_space_area = 0
        total_spaces = 0
        for floor in floors:
            display = floor["DisplayName"] or floor["FloorName"]
            if floor["FloorCode"]:
                display = f"[{floor['FloorCode']}] {display}"
            spaces = db.fetch_all("""
                SELECT r.*, p.PackageName FROM tblRoom r
                LEFT JOIN mstPackage p ON r.PackageID = p.PackageID
                WHERE r.FloorID=? ORDER BY r.RoomID
            """, (floor["FloorID"],))
            floor_area = floor["BuiltUpArea"] or 0
            allocated = sum(s["Area"] or 0 for s in spaces)
            remaining = floor_area - allocated
            coverage = int(round(allocated / floor_area * 100)) if floor_area else 0
            total_floor_area += floor_area
            total_space_area += allocated
            total_spaces += len(spaces)

            story.append(Paragraph(f"<b>{display}</b>  —  Built-up Area: {floor_area:.0f} sq.ft.  |  "
                                   f"Allocated: {allocated:.0f} sq.ft.  |  Remaining: {remaining:.0f} sq.ft.  |  "
                                   f"Coverage: {coverage}%", styles["ADSBody"]))
            story.append(Spacer(1, 3))

            if spaces:
                rows = [["Space", "Area (sq.ft.)", "Package", "Status"]]
                for s in spaces:
                    rows.append([s["RoomName"], f"{s['Area']:.0f}" if s["Area"] else "0",
                                 (s["PackageName"] or "—").replace("Building Planning", "Planning"),
                                 s["DesignStatus"]])
                t = Table(rows, colWidths=[60 * mm, 30 * mm, 35 * mm, 35 * mm])
                t.setStyle(_table_style(header_bg=MUTED, font_size=8.5))
                story.append(t)
            story.append(Spacer(1, 8))

        overall_coverage = int(round(total_space_area / total_floor_area * 100)) if total_floor_area else 0
        story.append(HRFlowable(width="100%", thickness=0.5, color=PARCHMENT, spaceAfter=4))
        story.append(Paragraph(f"<b>Project Total</b> — {len(floors)} floor(s), {total_spaces} space(s)  |  "
                               f"Built-up Area: {total_floor_area:.0f} sq.ft.  |  "
                               f"Allocated: {total_space_area:.0f} sq.ft.  |  Overall Coverage: {overall_coverage}%",
                               styles["ADSBody"]))

    # ---------------- Site Visit Summary ----------------
    if site_visits:
        story.append(Paragraph("Site Visit Summary", styles["ADSSection"]))
        rows = [["Date", "Purpose", "Status", "Distance", "Charge"]]
        for v in site_visits:
            rows.append([v["VisitDate"], v["Purpose"] or "—", v["Status"],
                        f"{v['Distance']} km" if v["Distance"] else "—",
                        f"₹{v['Charge']:.0f}" if v["Charge"] else "—"])
        t = Table(rows, colWidths=[25 * mm, 55 * mm, 25 * mm, 25 * mm, 25 * mm])
        t.setStyle(_table_style(header_bg=INK, font_size=8.5))
        story.append(t)

    if project["Remarks"]:
        story.append(Paragraph("Remarks", styles["ADSSection"]))
        story.append(Paragraph(project["Remarks"], styles["ADSBody"]))

    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    return output_path


def generate_proposal_pdf(proposal_id, output_path):
    """
    Builds the client-facing Proposal PDF. Everything commercial (Sub Total,
    GST, Total) comes directly from the linked Fee Calculation -- never
    recalculated here, so the Proposal always matches Fee Calculator exactly.
    Deliverables come from the real Package assembly logic (Sprint 1), not a
    fabricated checklist.
    """
    styles = _get_styles()

    proposal = db.fetch_one("SELECT * FROM trxProposal WHERE ProposalID=?", (proposal_id,))
    if not proposal:
        raise ValueError(f"Proposal {proposal_id} not found")

    project = db.fetch_one("""
        SELECT p.*, c.ClientName, c.Address AS ClientAddress, c.City, c.State,
               sec.SectorName, svc.ServiceName
        FROM tblProject p JOIN tblClient c ON p.ClientID = c.ClientID
        LEFT JOIN mstSector sec ON p.SectorID = sec.SectorID
        LEFT JOIN mstService svc ON p.ServiceID = svc.ServiceID
        WHERE p.ProjectID = ?
    """, (proposal["ProjectID"],))

    calc = None
    calc_items = []
    if proposal["CalculationID"]:
        calc = db.fetch_one("SELECT * FROM trxFeeCalculation WHERE CalculationID=?", (proposal["CalculationID"],))
        calc_items = db.fetch_all("""
            SELECT i.*, s.ServiceName FROM trxFeeCalculationItem i
            JOIN mstService s ON i.ServiceID = s.ServiceID WHERE i.CalculationID=?
        """, (proposal["CalculationID"],))

    payment_terms = db.fetch_all(
        "SELECT * FROM trxProposalPaymentTerm WHERE ProposalID=? ORDER BY StageOrder", (proposal_id,))

    # Real deliverables from the package the proposal was actually created
    # with (snapshotted at creation, per BR-002's copy-not-reference
    # discipline) -- NOT the project's current package, which may have
    # changed since. Proposals created before this fix (v4.4.3) have no
    # snapshot; for those specific legacy rows only, fall back to the
    # project's current package since there's no way to recover what was
    # actually true at the time.
    effective_package_id = proposal["PackageID"] or project["DefaultPackageID"]
    deliverables_by_category = {}
    if effective_package_id:
        deliverables_by_category = _assemble_package_deliverables(effective_package_id)

    doc = SimpleDocTemplate(output_path, pagesize=A4,
                            topMargin=18 * mm, bottomMargin=18 * mm,
                            leftMargin=20 * mm, rightMargin=20 * mm)
    story = []

    if os.path.exists(LOGO_PATH):
        story.append(Image(LOGO_PATH, width=50 * mm, height=(50 * mm * 311 / 906)))
        story.append(Spacer(1, 8 * mm))

    story.append(Paragraph("PROPOSAL", styles["ADSTitle"]))
    story.append(Paragraph(f"{proposal['ProposalNo']}  ·  Rev. {proposal['RevisionNo']}  ·  "
                           f"{proposal['ProposalDate']}  ·  Valid till {proposal['ValidTill'] or '-'}",
                           styles["ADSSubtitle"]))
    story.append(HRFlowable(width="100%", thickness=1, color=BRASS, spaceAfter=10))

    story.append(Paragraph("Prepared For", styles["ADSSection"]))
    story.append(_info_table([
        ("Client", project["ClientName"]),
        ("Project", project["ProjectName"]),
        ("Sector / Service", f"{project['SectorName'] or '-'} / {project['ServiceName'] or '-'}"),
        ("Site Address", project["SiteAddress"] or "-"),
    ]))

    if proposal["CoverLetter"]:
        story.append(Paragraph("Introduction", styles["ADSSection"]))
        story.append(Paragraph(proposal["CoverLetter"].replace("\n", "<br/>"), styles["ADSBody"]))

    if proposal["ScopeOfWork"]:
        story.append(Paragraph("Scope of Work", styles["ADSSection"]))
        story.append(Paragraph(proposal["ScopeOfWork"].replace("\n", "<br/>"), styles["ADSBody"]))

    if deliverables_by_category:
        story.append(Paragraph("Deliverables", styles["ADSSection"]))
        for category, items in deliverables_by_category.items():
            story.append(Paragraph(f"<b>{category}</b>", styles["ADSBody"]))
            for item in items:
                story.append(Paragraph(f"&bull; {item}", styles["ADSBody"]))
            story.append(Spacer(1, 4))

    if calc:
        story.append(Paragraph("Commercial Summary", styles["ADSSection"]))
        rows = [["Service", "Rate/Sq.ft (₹)", "Scope %", "Amount (₹)"]]
        for item in calc_items:
            rows.append([item["ServiceName"], f"{item['RatePerSqft']:,.2f}", f"{item['ScopePercent']:.0f}%",
                        f"{item['Amount']:,.2f}"])
        t = Table(rows, colWidths=[65 * mm, 35 * mm, 25 * mm, 35 * mm])
        t.setStyle(_table_style(header_bg=INK))
        story.append(t)
        story.append(Spacer(1, 6))

        sub_total = sum(i["Amount"] for i in calc_items)
        summary_rows = [("Sub Total", f"₹{sub_total:,.2f}")]
        if calc["DiscountPercent"]:
            discount_amount = sub_total * calc["DiscountPercent"] / 100
            summary_rows.append((f"Discount ({calc['DiscountPercent']:.1f}%)", f"-₹{discount_amount:,.2f}"))
        if calc["AdditionalDiscount"]:
            summary_rows.append(("Additional Discount", f"-₹{calc['AdditionalDiscount']:,.2f}"))
        summary_rows.append((f"GST ({calc['GSTPercent']:.0f}%)", "Included below"))
        summary_rows.append(("Total Professional Fee", f"₹{calc['TotalFee']:,.2f}"))
        story.append(_info_table(summary_rows, col_widths=(80 * mm, 80 * mm)))

    if payment_terms:
        story.append(Paragraph("Payment Terms", styles["ADSSection"]))
        rows = [["Stage", "%", "Amount (₹)"]]
        total_fee = calc["TotalFee"] if calc else 0
        for term in payment_terms:
            amount = total_fee * term["Percent"] / 100
            rows.append([term["StageName"], f"{term['Percent']:.0f}%", f"{amount:,.2f}"])
        t = Table(rows, colWidths=[90 * mm, 30 * mm, 40 * mm])
        t.setStyle(_table_style(header_bg=MUTED))
        story.append(t)

    if proposal["TermsConditions"]:
        story.append(Paragraph("Terms & Conditions", styles["ADSSection"]))
        story.append(Paragraph(proposal["TermsConditions"].replace("\n", "<br/>"), styles["ADSBody"]))

    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    return output_path


def _assemble_package_deliverables(package_id):
    """
    Walks the ParentPackageID inheritance chain from root to the given
    package, unioning all deliverables and applying SupersedesDeliverableID
    overrides so upgraded items replace their older version instead of
    duplicating. Same logic as migrate_packages.py's get_assembled_package,
    ported here using the shared db module instead of a standalone
    connection, since this needs to run as part of the live app.
    """
    chain = []
    current_id = package_id
    while current_id is not None:
        pkg = db.fetch_one("SELECT * FROM mstPackage WHERE PackageID=?", (current_id,))
        if not pkg:
            break
        chain.append(pkg)
        current_id = pkg["ParentPackageID"]
    chain.reverse()

    superseded_ids = set()
    all_deliverables = []
    for pkg in chain:
        for d in db.fetch_all("SELECT * FROM mstDeliverable WHERE PackageID=? AND Active=1", (pkg["PackageID"],)):
            if d["SupersedesDeliverableID"]:
                superseded_ids.add(d["SupersedesDeliverableID"])
            all_deliverables.append(d)

    result = {}
    for d in all_deliverables:
        if d["DeliverableID"] in superseded_ids:
            continue
        result.setdefault(d["Category"], []).append(
            d["Deliverable"] + (" (Optional)" if d["IsOptional"] else "")
        )
    return result


def _table_style(header_bg, font_size=9):
    return TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), header_bg),
        ("TEXTCOLOR", (0, 0), (-1, 0), WHITE),
        ("FONTNAME", (0, 0), (-1, 0), FONT_BOLD),
        ("FONTNAME", (0, 1), (-1, -1), FONT_REGULAR),
        ("FONTSIZE", (0, 0), (-1, -1), font_size),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("GRID", (0, 0), (-1, -1), 0.4, PARCHMENT),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ])
